### ISSUE TITLE
getFile in a remote folder doesn't appear to work

### ISSUE THREAD

**Issue by jmaton** [eflexsystems/node-samba-client#24]
First and foremost, thank you very much for this library!  :-)

Consider, the address is: \\\\theaddress\\myshare
Inside that there is a folder named "foo", and in the foo folder there is a file "bar".

I want that file so I do this:

```
let client = new SambaClient('\\\\theaddress\\myshare, 'myuser', 'mypass', '', 'SMB3');
client.getFile('foo/bar', 'localbar);
```

This fails with an ENOENT. The command it's running is actually:
`smbclient -U 'myuser' -c 'get bar localbar' //theaddress/myshare 'mypass' --max-protocol SMB3`

i.e., it strips the folder.

This is due to the code in "runCommand"; it interprets the remote folder as the local working directory:

```
runCommand(cmd, path, destination) {
    let workingDir = p.dirname(path);
    let fileName = p.basename(path).replace(singleSlash, '\\');
    let cmdArgs = util.format('%s %s', fileName, destination);

    return this.execute(cmd, cmdArgs, workingDir);
  }
```

I tweaked getFile and sendFile slightly (and deleted runCommand) :

```
  getFile(path, destination, workingDir) {
    let fileName = path.replace(singleSlash, '\\');
    let cmdArgs = util.format('%s %s', fileName, destination);
    return this.execute('get', cmdArgs, workingDir);
  }

  sendFile(path, destination) {
    let workingDir = p.dirname(path);
    let fileName = p.basename(path).replace(singleSlash, '\\');
    let cmdArgs = util.format('%s %s', fileName, destination.replace(singleSlash, '\\'));
    return this.execute('put', cmdArgs, workingDir);
  }
```

also in function "execute" I tweaked this line based on the pull request https://github.com/eflexsystems/node-samba-client/pull/20
```
    let options = {
      cwd: (workingDir ? workingDir : '')
    };

```

May I check in these fixes?

Again, thank you for this library.

**Comment by jakesjews** [comment]
@jmaton no problem. A PR would be awesome thanks!

**Comment by secolinsky** [comment]
jmaton, thanks for this post.  I was having similar problems on my ubuntu machine getting the file from the samba server, with node giving an ENOENT error.  Your changes to the getFile fixed my problem.  

I was having trouble understanding why the code needs a wrap function.  It seem's a bit peculiar.  Either way, it's needed because it can't work if I take the wrap out.

**Comment by jmaton** [comment]
Hi @jakesjews , I have been trying to push my change tonight but I'm getting 
 ERROR: Permission to eflexsystems/node-samba-client.git denied to jmaton.

Do you need to do anything to allow me to push, or is this entirely on my end?  :)

**Comment by jmaton** [comment]
I forked, pushed, and created a pull request.  Thanks again for such a wonderful library.

**Comment by nateevans** [comment]
fixed in https://github.com/eflexsystems/node-samba-client/pull/27

**Comment by thault** [comment]
This seems to have reared up again, I'm trying to send a file from the tmp folder and it's stripping out the folder. 
`await client.sendFile('/tmp/c023dc82-d4fd-4bd8-a5ee-619f73104bf9.jpg', '\\testimage.jpg');`
Shows up in logs: 
`-c put \"c023dc82-d4fd-4bd8-a5ee-619f73104bf9.jpg\" \"\\testimage.jpg\"`
