### ISSUE TITLE
Breaking changes in smbclient > 4.12.15-r0

### ISSUE THREAD

**Issue by olekristensen** [eflexsystems/node-samba-client#43]
Hi there,

We've experienced some breaking changes in the samba-client apk in alpine > 3.12, where the samba-client version is above 4.12.15-r0

One change that we've located is that a password set in the end of the command does not work, it has to be passed with --password to the smbclient.

Other changes are a bit more hard to debug, and we've resorted to pinning our node:alpine container at alpine3.12 for now.

It seems that smbclient is rather alive and the samba project does not value consistency in the api for it.

I would propose that the readme includes a line about last known version of smbclient that has been tested and found working.

And that we look into where we're at with samba-client version 4.15.2-r0

**Comment by jakesjews** [comment]
Oh geeze. Could you open up a PR with the change and ill merge it in

**Comment by jakesjews** [comment]
I bet that bug affects the app im working on as well so thanks a ton for this bug report!

**Comment by silentroach** [comment]
@jakesjews can you please review, merge and publish the new version?

**Comment by jakesjews** [comment]
Released as version 5.0.0
